{% set name = "google-cloud-runtimeconfig" %}
{% set version = "0.34.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-runtimeconfig-{{ version }}.tar.gz
  sha256: 872c6f4c28710860ba6238ef606a9a243be005bbdeec48f37cf10b97e2c1d83f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - google-cloud-core >=1.4.4,<3.0dev

test:
  imports:
    - google.cloud.client
    - google.cloud.runtimeconfig
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-runtimeconfig
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud RuntimeConfig API client library
  description: "The Google Cloud RuntimeConfig API enables developers to dynamically configure and expose variables through Google Cloud Platform. In addition, you can also set Watchers and Waiters that will watch for changes to your data and return based on certain conditions.\nSee the [quick start guide](https://googleapis.dev/python/runtimeconfig/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/runtimeconfig/latest/index.html
  dev_url: https://github.com/googleapis/python-runtimeconfig

extra:
  recipe-maintainers:
    - xylar
    - parthea
