schema_version: 1

context:
  name: google-cloud-runtimeconfig
  version: "0.37.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: b4425a4dd8f201c7ef08e19515653abe839b86054cdc796e92c688605a3d3afc

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - google-cloud-core >=1.4.4,<3.0.0

tests:
  - python:
      imports:
        - google.cloud.client
        - google.cloud.runtimeconfig
      python_version: ${{ python_min }}.*
      pip_check: true

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: Google Cloud RuntimeConfig API client library
  description: |
    The Google Cloud RuntimeConfig API enables developers to dynamically configure and expose variables through Google Cloud Platform. In addition, you can also set Watchers and Waiters that will watch for changes to your data and return based on certain conditions.
    See the [quick start guide](https://googleapis.dev/python/runtimeconfig/latest/index.html#quick-start).

  homepage: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-runtimeconfig
  repository: https://github.com/googleapis/google-cloud-python/tree/main/packages/google-cloud-runtimeconfig
  documentation: https://googleapis.dev/python/runtimeconfig/latest/index.html

extra:
  recipe-maintainers:
    - xylar
    - parthea
